Repository Turing-Eras/api, pull requests merged in 2020-12, with the labels that each got.

#26 Setup
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/graphql_controller.rb
  app/graphql/api_schema.rb
  app/graphql/mutations/.keep
  app/graphql/mutations/base_mutation.rb
  app/graphql/types/.keep
  app/graphql/types/base_argument.rb
  app/graphql/types/base_enum.rb
  app/graphql/types/base_field.rb
  app/graphql/types/base_input_object.rb
  app/graphql/types/base_interface.rb
  app/graphql/types/base_object.rb
  app/graphql/types/base_scalar.rb
  app/graphql/types/base_union.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  bin/rails
  bin/rake
  bin/setup
  bin/spring
  config.ru
  config/application.rb
  config/boot.rb
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/filter_parameter_logging.rb
  config/puma.rb
  config/routes.rb
  db/seeds.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: BEE

#37 Get users
  app/assets/config/manifest.js
  app/graphql/types/query_type.rb
  app/graphql/types/user_type.rb
  config/application.rb
  config/routes.rb
  db/seeds.rb
  spec/requests/graphql/queries/users/get_single_user_spec.rb
  spec/requests/graphql/queries/users/get_users_spec.rb
Labels: BEE

#45 Fix Heroku Deployment Bug
  .gitignore
  app/assets/config/manifest.js
  config/application.rb
Labels: BEE, bug

#49 Create test factories for user, events, and eras
  Gemfile
  Gemfile.lock
  spec/factories/eras.rb
  spec/factories/events.rb
  spec/factories/users.rb
  spec/rails_helper.rb
  spec/requests/graphql/mutations/update_user_spec.rb
  spec/requests/graphql/queries/users/get_single_user_spec.rb
  spec/requests/graphql/queries/users/get_users_spec.rb
Labels: BEE, testing
