Repository Turing-Eras/api, pull requests merged in 2021-01, with the labels that each got.

#56 Add eras to User Type
  README.md
  app/graphql/types/era_type.rb
  app/graphql/types/user_type.rb
  spec/requests/graphql/mutations/update_user_spec.rb
  spec/requests/graphql/queries/users/get_single_user_spec.rb
  spec/requests/graphql/queries/users/get_users_spec.rb
Labels: BEE

#58 Get events
  Gemfile.lock
  app/graphql/types/event_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/user_type.rb
  spec/requests/graphql/queries/events/get_single_event_spec.rb
  spec/requests/graphql/queries/users/get_single_user_spec.rb
Labels: BEE, review

#62 Delete Era, Clean up of other Specs
  Gemfile.lock
  app/graphql/mutations/eras/delete_era.rb
  app/graphql/types/mutation_type.rb
  spec/requests/graphql/mutations/delete_eras_spec.rb
  spec/requests/graphql/mutations/update_user_spec.rb
  spec/requests/graphql/queries/users/get_single_user_spec.rb
Labels: BEE, eras, testing

#63 Get era by ID
  app/graphql/types/query_type.rb
  spec/factories/eras.rb
  spec/requests/graphql/queries/eras/get_single_era_spec.rb
Labels: BEE

#65 Seeds
  db/seeds.rb
  spec/factories/events.rb
Labels: BEE, database

#68 Datetime to date
  Gemfile.lock
  db/migrate/20201219223436_create_users.rb
  db/migrate/20201219223722_create_eras.rb
  db/migrate/20201219223849_create_events.rb
  db/schema.rb
  spec/requests/graphql/mutations/update_user_spec.rb
Labels: BEE, database

#69 Update era
  app/graphql/mutations/eras/update_era.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  spec/requests/graphql/mutations/eras/update_era_spec.rb
  spec/requests/graphql/mutations/update_event_spec.rb
  spec/requests/graphql/mutations/users/update_user_spec.rb
Labels: BEE

#72 Add more details to README, Update Seeds
  Gemfile
  Gemfile.lock
  README.md
  db/seeds.rb
  schema.png
Labels: BEE, documentation

#73 Create era
  app/graphql/api_schema.rb
  app/graphql/mutations/eras/create_era.rb
  app/graphql/types/mutation_type.rb
  app/models/concerns/dates_in_past_validator.rb
  app/models/era.rb
  spec/requests/graphql/mutations/eras/create_era_spec.rb
  spec/spec_helper.rb
Labels: BEE

#81 Week number to events and eras
  db/migrate/20201219223722_create_eras.rb
  db/migrate/20201219223849_create_events.rb
  db/schema.rb
Labels: BEE, database

#83 Onboarding questions
  app/graphql/types/query_type.rb
  app/graphql/types/question_type.rb
  app/models/question.rb
  db/migrate/20210105214942_add_name_to_questions.rb
  db/schema.rb
  db/seeds.rb
  spec/models/question_spec.rb
  spec/requests/graphql/queries/questions/get_questions_spec.rb
Labels: BEE

#84 Era week number test
  app/graphql/mutations/eras/create_era.rb
  app/graphql/mutations/eras/update_era.rb
  app/graphql/types/era_type.rb
  app/models/era.rb
  spec/factories/eras.rb
  spec/factories/events.rb
  spec/factories/users.rb
  spec/models/era_spec.rb
  spec/requests/graphql/mutations/eras/create_era_spec.rb
  spec/requests/graphql/mutations/eras/delete_eras_spec.rb
  spec/requests/graphql/mutations/eras/update_era_spec.rb
  spec/requests/graphql/mutations/events/delete_event_spec.rb
  spec/requests/graphql/mutations/events/update_event_spec.rb
  spec/requests/graphql/queries/eras/get_single_era_spec.rb
Labels: BEE, database, eras, testing

#93 Add rack-cors, and update cors.rb file
  Gemfile
  Gemfile.lock
  config/initializers/cors.rb
Labels: BEE

#96 Add `require factory_bot_rails` to spec_helper to attempt to fix seed
  spec/spec_helper.rb
Labels: BEE, database

#97 Fix deployment bug
  .gitignore
  Rakefile
  app/assets/config/manifest.js
  config/application.rb
Labels: bug, deployment

#92 Create events
  app/graphql/mutations/events/create_event.rb
  app/graphql/mutations/events/delete_event.rb
  app/graphql/mutations/events/update_event.rb
  app/graphql/types/era_type.rb
  app/graphql/types/event_type.rb
  app/graphql/types/mutation_type.rb
  app/models/event.rb
  spec/factories/users.rb
  spec/models/event_spec.rb
  spec/requests/graphql/mutations/eras/create_era_spec.rb
  spec/requests/graphql/mutations/eras/update_era_spec.rb
  spec/requests/graphql/mutations/events/create_event_spec.rb
  spec/requests/graphql/mutations/events/update_event_spec.rb
  spec/requests/graphql/queries/eras/get_single_era_spec.rb
  spec/requests/graphql/queries/events/get_single_event_spec.rb
Labels: BEE

#100 Move factory_bot_rails
  Gemfile
Labels: BEE, bug, database

#104 Adds event type to question type file
  app/graphql/types/question_type.rb
Labels: BEE

#108 Readme final, Rubocop fixes
  README.md
  app/models/concerns/dates_in_past_validator.rb
  eras-logo-horizontal.png
  schema.png
Labels: BEE, refactor, work in progress

#114 Bug fix: set color using .blank instead of .empty
  app/graphql/mutations/eras/create_era.rb
  app/graphql/mutations/events/create_event.rb
Labels: BEE, bug

#113 Add FE deployed app to readme
  README.md
Labels: BEE, documentation

#118 Add code fair video to readme
  README.md
Labels: documentation
